"""Create trips and voyages tables

Revision ID: 6f3e87163450
Revises:
Create Date: 2025-10-26 11:41:31.917384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f3e87163450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_version_roundtrip', sa.String(), nullable=False),
    sa.Column('origin_service_master', sa.String(), nullable=False),
    sa.Column('dest_service_master', sa.String(), nullable=False),
    sa.Column('corridor', sa.String(), nullable=False),
    sa.Column('latest_origin_departure', sa.DateTime(), nullable=False),
    sa.Column('week_start_date', sa.DateTime(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('capacity_teu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_version_roundtrip', 'origin_service_master', 'dest_service_master', name='uq_voyage_composite')
    )
    op.create_index(op.f('ix_voyages_corridor'), 'voyages', ['corridor'], unique=False)
    op.create_index('ix_voyages_corridor_week', 'voyages', ['corridor', 'week_start_date'], unique=False)
    op.create_index(op.f('ix_voyages_week_start_date'), 'voyages', ['week_start_date'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voyage_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('origin_port_code', sa.String(), nullable=False),
    sa.Column('destination_port_code', sa.String(), nullable=False),
    sa.Column('origin_at_utc', sa.DateTime(), nullable=False),
    sa.Column('offered_capacity_teu', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_origin'), 'trips', ['origin'], unique=False)
    op.create_index(op.f('ix_trips_voyage_id'), 'trips', ['voyage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_voyage_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_origin'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_voyages_week_start_date'), table_name='voyages')
    op.drop_index('ix_voyages_corridor_week', table_name='voyages')
    op.drop_index(op.f('ix_voyages_corridor'), table_name='voyages')
    op.drop_table('voyages')
    # ### end Alembic commands ###
